prgrms-aibe-devcourse/AIBE1_FinalProject_LastDance_FE

src/components/games/GameSetupModal.tsx

- feat: 게임 참여자 설정에 그룹원 이름 드롭다운 추가

feat: 게임 참여자 설정에 그룹원 이름 드롭다운 추가

---

src/components/calendar/CalendarPage.tsx
src/hooks/useCalendar.ts

refector: calendar

---

src/api/admin.ts
src/api/expense.ts
src/components/admin/ai/AISystemManagement.tsx
src/components/expenses/ExpensesPage.tsx
src/hooks/useAdmin.ts

- feature: LLM 지출분석 만족도 추이 표시
- 기존의 AiJudgement와는 동일페이지에 2개의 탭으로 구성함.

feat: LLM 지출분석 만족도 추이 표시

---

index.html
src/components/expenses/ExpenseModal.tsx
src/components/expenses/ExpensesPage.tsx

fix: 모달 컬러 수정

---

src/components/layout/Footer.tsx

- feature: 로그인 API 개발
- fix: 잘못된 날짜 포맷 파싱 문제 해결

refector: footer

---

src/components/community/CommunityPage.tsx
src/components/community/PostCard.tsx
src/components/community/PostDetail.tsx
src/components/community/PostDetailPage.tsx

refactor: 커뮤니티 페이지 디자인 수정

---

src/components/community/CommunityPage.tsx
src/components/community/PostCard.tsx
src/components/expenses/ExpensesPage.tsx

refactor: 커뮤니티 페이지 디자인 수정2

---

package.json
public/robots.txt
public/sitemap.xml
src/components/admin/analytics/AnalyticsPage.tsx
src/components/admin/content/ContentManagement.tsx
src/components/admin/dashboard/AdminDashboard.tsx
src/components/admin/reports/ReportManagement.tsx
src/components/ai/ConflictInputModal.tsx
src/components/ai/HistorySidebar.tsx
src/components/ai/ModeToggleSidebar.tsx
src/components/ai/ResultDisplay.tsx
src/components/ai/TipsModal.tsx
src/components/community/CommunityPage.tsx
src/components/community/PostCard.tsx
src/components/community/PostDetail.tsx
src/components/community/ReportModal.tsx
src/components/expenses/ExpensesPage.tsx
src/components/games/DartsGame.tsx
src/components/games/GamesPage.tsx
src/components/games/GroupGameHistory.tsx
src/components/games/MemoryGamePage.tsx
src/components/games/QuizGame.tsx
src/components/games/RockPaperScissorsPage.tsx
src/components/groups/GroupSettingsModal.tsx
src/components/home/LandingPage.tsx
src/components/tasks/TaskModal.tsx
vite.config.ts

fix: 게임 결과, 할일 추가 모달, 색상 변경

---

src/components/youthpolicy/YouthPolicyCard.tsx
src/components/youthpolicy/YouthPolicyDetailPage.tsx
src/components/youthpolicy/YouthPolicyList.tsx
src/index.css

fix: 청년정책 수정

---

src/components/home/HomePage.tsx
src/components/layout/Footer.tsx
src/components/legal/LegalModal.tsx

- fix: 불필요한 아이콘 제거
- fix: 로고옆 텍스트 추가
- fix: 각 링크 연결

fix: 로고텍스트 및 링크 연결

---

src/components/ai/AIAssistantPage.tsx
src/components/ai/ConflictInputModal.tsx
src/components/ai/HistorySidebar.tsx
src/components/ai/MiniTipsModal.tsx
src/components/ai/ResultDisplay.tsx
src/components/ai/TipsModal.tsx

refactor: 컬러 수정 및 스피너 수정

---

src/components/community/CommunityPage.tsx

refactor: dev 병합

---

src/components/dashboard/DashboardPage.tsx

- refactor: 할일 오늘자 기능으로 안뜨던 오류 수정

refactor: 할일 오늘자 기능으로 안뜨던 오류 수정

---

src/components/tasks/TasksPage.tsx

fix: 할일 그룹 이름 수 제한

---

src/components/calendar/CalendarPage.tsx
src/components/calendar/EventModal.tsx
src/components/home/HomePage.tsx
src/components/layout/Header.tsx
src/hooks/useNotifications.ts

refector: calendar 디자인 재수정

---

src/components/tasks/TaskModal.tsx

fix: 할일 추가 모달 우선순위

---

src/components/community/CommunityPage.tsx

fix: 글 쓰기 버튼 출력되던 오류 수정

---

src/components/expenses/ExpensesPage.tsx

> fix: 지출내역 없는 사용자 조회 중 오류 해결
- fix: 지출내역 없는 사용자 조회 중 오류 해결
- 이 PR은 #78 와 연결됨

fix: 지출내역 없는 사용자 조회 중 오류 해결

---

src/components/calendar/CalendarPage.tsx
src/components/calendar/EventModal.tsx
src/components/layout/Header.tsx

- feature: 로그인 API 개발
- fix: 잘못된 날짜 포맷 파싱 문제 해결

dev to main

---

src/components/home/HomePage.tsx

feat: 홈페이지에 청년정책 소개칸 작성

---

src/components/tasks/TasksPage.tsx

fix: 할일 도넛 위치

---

src/components/expenses/ExpensesPage.tsx

fix: 월이동시 분담금 표시 수정

---

src/components/home/HomePage.tsx

feat: 메인페이지 이미지 추가

---

src/components/home/HomePage.tsx
src/components/home/LandingPage.tsx
tailwind.config.js

fix: 메인페이지 이미지 크기 변경

---

README.md

- docs: 시스템 아키텍쳐 추가
- 이 PR은 #179 와 연결됨

docs: 시스템 아키텍쳐 추가

---

src/components/home/HomePage.tsx
src/components/home/LandingPage.tsx

feat:메인 페이지 사진 추가

---

src/components/home/HomePage.tsx

fix: 그룹 소개글 자세히보기 경로 수정

---

src/components/settings/SettingsPage.tsx

refector: 알림설정 방식에 따른 로직 추가

---

check-backend.js
vercel.json
vite.config.ts

fix: vercel 오류

---

src/components/groups/CreateGroupModal.tsx
src/components/groups/GroupSettingsModal.tsx

- feature: 로그인 API 개발
- fix: 잘못된 날짜 포맷 파싱 문제 해결

fix: 그룹 버그 수정

---

src/api/calendar.ts

[fix] groupid 파라미터로 추가
